SUCCESS\
assertion failed: p.sum() == a.wrapping_add(b)
