Checking harness check_box...

Status: SUCCESS\
Description: "Panic: assertion failed: boxed.ref_id() == id"\
in function check_box

Status: SUCCESS\
Description: "Panic: assertion failed: boxed.box_id() == id"\
in function check_box


Status: SUCCESS\
Description: "Panic: assertion failed: self.as_ref().id == self.id"\
in function <Concrete as Trait>::box_id

VERIFICATION:- SUCCESSFUL


Checking harness check_rc...

Status: SUCCESS\
Description: "Panic: assertion failed: ref_count.ref_id() == id"\
in function check_rc

Status: SUCCESS\
Description: "Panic: assertion failed: ref_count.rc_id() == id"\
in function check_rc


Status: SUCCESS\
Description: "Panic: assertion failed: self.as_ref().id == self.id"\
in function <Concrete as Trait>::rc_id

VERIFICATION:- SUCCESSFUL


Checking harness check_arc...

Status: SUCCESS\
Description: "Panic: assertion failed: async_ref.ref_id() == id"\
in function check_arc

Status: SUCCESS\
Description: "Panic: assertion failed: async_ref.arc_id() == id"\
in function check_arc


Status: SUCCESS\
Description: "Panic: assertion failed: self.as_ref().id == self.id"\
in function <Concrete as Trait>::arc_id

VERIFICATION:- SUCCESSFUL


Checking harness check_pin...

Status: SUCCESS\
Description: "Panic: assertion failed: pin.ref_id() == id"\
in function check_pin

Status: SUCCESS\
Description: "Panic: assertion failed: pin.pin_id() == id"\
in function check_pin

Status: SUCCESS\
Description: "Panic: assertion failed: self.as_ref().id == self.id"\
in function <Concrete as Trait>::pin_id


VERIFICATION:- SUCCESSFUL

Checking harness check_pin_box...

Status: SUCCESS\
Description: "Panic: assertion failed: pin.ref_id() == id"\
in function check_pin_box

Status: SUCCESS\
Description: "Panic: assertion failed: pin.pin_box_id() == id"\
in function check_pin_box

Status: SUCCESS\
Description: "Panic: assertion failed: self.as_ref().id == self.id"\
in function <Concrete as Trait>::pin_box_id

VERIFICATION:- SUCCESSFUL


Checking harness check_mut...

Status: SUCCESS\
Description: "Panic: assertion failed: trt.replace_id(new_id) == initial_id"\
in function check_mut

Status: SUCCESS\
Description: "Panic: assertion failed: trt.ref_id() == new_id"\
in function check_mut

VERIFICATION:- SUCCESSFUL


Checking harness check_bound...

Status: SUCCESS\
Description: "Panic: assertion failed: obj.bound_value() == id"\
in function check_bound::assert_value::<Concrete>

VERIFICATION:- SUCCESSFUL
