line 8 assertion failed: foo() == None: SUCCESS
line 11 assertion failed: foo() == y: SUCCESS
