[estimate_size.assertion.1] line 17 Oh no, a failing corner case!: FAILURE
