assertion failed: p.sum() == 3: SUCCESS
