forloop::{closure#0}.assertion.1\
         - Status: SUCCESS\
         - Description: "attempt to multiply with overflow"

forloop.loop_invariant_step.2\
         - Status: SUCCESS\
         - Description: "Check invariant after step for loop forloop.0"

forloop.assertion.3\
         - Status: SUCCESS\
         - Description: "assertion failed: sum <= 2550"

VERIFICATION:- SUCCESSFUL
